# These are supported funding model platforms

github: ['tahaghafuri']# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ['https://fenjoun.com/tag','https://tagteach.ir/']# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
